In [1]:
import pandas as pd
from pyproj import CRS, Transformer
import autoroot
from rs_tools._src.utils.io import get_list_filenames, get_list_filenames_af
from rs_tools._src.geoprocessing.match import match_timestamps_af
from pathlib import Path   
import numpy as np 
import xarray as xr
from satpy.scene import Scene
from pyhdf.SD import SD, SDC 
import pandas as pd
import cartopy.crs as ccrs
import rioxarray
import numpy as np
import matplotlib.pyplot as plt
import os
from datetime import datetime
import fnmatch
from pyproj import CRS, Transformer
from pyhdf.SD import SD, SDC 
import gc
from datetime import timedelta
import glob
%load_ext autoreload
%autoreload 2

/home/sgirtsou/miniconda3/envs/rs_tools/lib/python3.11/site-packages/pyproj/__init__.py:95: UserWarning: pyproj unable to set database path.
  _pyproj_global_context_initialize()
/home/sgirtsou/miniconda3/envs/rs_tools/lib/python3.11/site-packages/goes2go/data.py:665: FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
  within=pd.to_timedelta(config["nearesttime"].get("within", "1h")),
/home/sgirtsou/miniconda3/envs/rs_tools/lib/python3.11/site-packages/goes2go/NEW.py:188: FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
  within=pd.to_timedelta(config["nearesttime"].get("within", "1h")),

In [2]:
def convert_lat_lon_to_x_y(crs, lon, lat):
    transformer = Transformer.from_crs(CRS("+proj=latlon"), crs, always_xy=True)
    x, y = transformer.transform(lon, lat)
    return x, y

def parse_af_dates_from_file(file):
    timestamp = Path(file).name.split("_")[0]
    return timestamp

In [3]:
def create_fires_ds(matching_modis_files, modis_dir, msg):
    array = np.zeros((msg.y.size, msg.x.size))
    var = "msg_seviri_fes_3km"
    crs_wkt = msg[var].crs_wkt
    crs = CRS(crs_wkt)
    print(os.path.join(modis_dir, matching_modis_files[0]))
    f = SD(os.path.join(modis_dir, matching_modis_files[0]), SDC.READ)
    df = pd.DataFrame()
    sds_obj = f.select('fire mask') # select sds
    fm_data = sds_obj.get() # get sds data

    if fm_data[fm_data > 6].shape[0] > 0:
        for key in ['FP_latitude', 
                        'FP_longitude', 
                        'FP_power']:

            sds_obj = f.select(key) 
            
            data = sds_obj.get()
            df[key] = data.ravel()
    
        for index, row in df.iterrows():
            lon = row['FP_longitude']
            lat = row['FP_latitude']
            x_sel, y_sel = convert_lat_lon_to_x_y(crs, lon, lat)
            selected = msg.sel(x=x_sel, y=y_sel, method='nearest')
            # Get the indices of the nearest point
            x_idx = msg.get_index('x').get_loc(selected['x'].item())
            y_idx = msg.get_index('y').get_loc(selected['y'].item())
            array[y_idx, x_idx] = 1
        da = xr.DataArray(
            array,
            coords={"y": msg.y, "x": msg.x},
            dims=("y", "x")
    )
    else:
        print('No fires detected')
        return None
    return da

In [11]:
fb = pd.read_excel('/mnt/data8tb/fire_detection/fire_brigade/Dasikes_Pyrkagies_2023_v1.8.xlsx', skiprows=1)
msg_path = '/mnt/outputs/geoprocessed'
save_msg_path = '/mnt/data8tb/fire_detection/fire_brigade/patched_msg'
save_af_path = '/mnt/data8tb/fire_detection/fire_brigade/patched_af'
if not os.path.exists(save_msg_path):
    os.makedirs(save_msg_path)
if not os.path.exists(save_af_path):
    os.makedirs(save_af_path)

In [4]:
fb['sum'] = fb[['Δάση',
       'Δασική Έκταση', 'Άλση', 'Χορτ/κές Εκτάσεις', 'Καλάμια - Βάλτοι',
       'Γεωργικές Εκτάσεις', 'Υπολλείματα Καλλιεργειών', 'Σκουπι-δότοποι']].sum(axis=1)
fd = fb.sort_values('sum', ascending=False)
fd_sub = fd[fd['sum'] > 10]
fd_sub['timestamp'] = pd.to_datetime(fd_sub['Ημερ/νία Έναρξης'].astype(str) + ' ' + fd_sub['Ώρα Έναρξης'].astype(str), 
                                 format='%Y-%m-%d %H:%M')

#remove 3 hours from timestamp
fd_sub['timestamp_ut'] = fd_sub['timestamp'] - pd.Timedelta(hours=3)
fd_sub['timestamp_ut_str'] = fd_sub['timestamp_ut'].dt.strftime('%Y%m%d%H%M00')
unique_times_fb = fd_sub['timestamp_ut'].dt.strftime('%Y%m%d%H%M00').unique().tolist()

/tmp/ipykernel_1336564/2519916280.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fd_sub['timestamp'] = pd.to_datetime(fd_sub['Ημερ/νία Έναρξης'].astype(str) + ' ' + fd_sub['Ώρα Έναρξης'].astype(str),
/tmp/ipykernel_1336564/2519916280.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fd_sub['timestamp_ut'] = fd_sub['timestamp'] - pd.Timedelta(hours=3)
/tmp/ipykernel_1336564/2519916280.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fd_sub['timestamp_ut_str'] = fd_sub['timestamp_ut'].dt.strftime('%Y%m%d%H%M00')

In [5]:
fd_sub

,Α/Α ΕΓΓΡΑΦΗΣ,Α/Α ENGAGE,X-ENGAGE,Y-ENGAGE,Υπηρεσία,Νομός,Ημερ/νία Έναρξης,Ώρα Έναρξης,Ημερ/νία Κατασβεσης,Ώρα Κατάσβεσης,...,Α/Φ CL415,Α/Φ CL215,Α/Φ PZL,Α/Φ GRU.,ΜΙΣΘ. ΕΛΙΚΟΠΤ.,ΜΙΣΘ. ΑΕΡΟΣΚ.,sum,timestamp,timestamp_ut,timestamp_ut_str
1274,1911773,1096267,26.175290,41.115503,Π.Κ. ΣΟΥΦΛΙΟΥ,ΕΒΡΟΥ,2023-08-21,13:05,2023-10-02,15:30,...,11,0,2,0,9.0,9.0,818348.00,2023-08-21 13:05:00,2023-08-21 10:05:00,20230821100500
6986,1907588,1084257,27.940565,36.232992,Π.Υ. ΡΟΔΟΥ,ΔΩΔΕΚΑΝΗΣΩΝ,2023-07-18,19:09,NaT,NaN,...,9,0,0,0,0.0,5.0,176398.00,2023-07-18 19:09:00,2023-07-18 16:09:00,20230718160900
980,1923198,1095402,26.078210,40.935618,Π.Υ. ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ,ΕΒΡΟΥ,2023-08-19,04:40,2023-09-25,20:19,...,11,0,2,0,9.0,12.0,122144.00,2023-08-19 04:40:00,2023-08-19 01:40:00,20230819014000
6730,1891011,1083804,23.498074,38.189420,Π.Υ. ΟΙΝΟΦΥΤΩΝ,ΒΟΙΩΤΙΑΣ,2023-07-17,17:08,2023-08-14,09:08,...,9,7,2,0,0.0,0.0,110000.00,2023-07-17 17:08:00,2023-07-17 14:08:00,20230717140800
3385,1897313,1087558,22.749670,39.367687,Π.Υ. ΒΙ.ΠΕ.ΒΟΛΟΥ,ΜΑΓΝΗΣΙΑΣ,2023-07-26,13:35,2023-08-19,20:47,...,0,0,0,0,0.0,0.0,86340.00,2023-07-26 13:35:00,2023-07-26 10:35:00,20230726103500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2120,1929726,1135712,22.331521,40.538138,Π.Υ. ΒΕΡΟΙΑΣ,ΗΜΑΘΙΑΣ,2023-12-23,17:35,2023-12-23,19:00,...,0,0,0,0,0.0,0.0,10.10,2023-12-23 17:35:00,2023-12-23 14:35:00,20231223143500
681,1895397,1099471,24.153976,41.111824,Π.Υ. ΔΡΑΜΑΣ,ΔΡΑΜΑΣ,2023-08-29,14:22,2023-08-29,16:05,...,0,0,0,0,0.0,0.0,10.10,2023-08-29 14:22:00,2023-08-29 11:22:00,20230829112200
3456,1869916,1070265,21.810887,39.567101,Π.Υ. ΤΡΙΚΑΛΩΝ,ΤΡΙΚΑΛΩΝ,2023-06-05,15:49,2023-06-05,16:55,...,0,0,0,0,0.0,0.0,10.05,2023-06-05 15:49:00,2023-06-05 12:49:00,20230605124900
536,1850111,1048876,24.707864,40.954719,Π.Υ. ΧΡΥΣΟΥΠΟΛΗΣ,ΚΑΒΑΛΑΣ,2023-03-13,10:33,NaT,NaN,...,0,0,0,0,0.0,0.0,10.05,2023-03-13 10:33:00,2023-03-13 07:33:00,20230313073300
619,1908598,1115253,24.616294,40.971173,Π.Υ. ΧΡΥΣΟΥΠΟΛΗΣ,ΚΑΒΑΛΑΣ,2023-10-10,13:29,2023-10-10,14:45,...,0,0,0,0,0.0,0.0,10.05,2023-10-10 13:29:00,2023-10-10 10:29:00,20231010102900

In [6]:
len(unique_times_fb)

862

In [7]:
#files_msg = get_list_filenames(msg_path, ".nc", "2023") #1min and 1.4sec

In [8]:
files_msg_af = get_list_filenames_af(msg_path, ".nc", "2023") #57.9sec

In [12]:
unique_times_msg = list(set(map(parse_af_dates_from_file, files_msg_af)))

In [13]:
len(unique_times_msg)

14124

In [14]:
df_matches = match_timestamps_af(unique_times_fb, unique_times_msg, cutoff=120)
df_matches.columns = ['timestamp_fb', 'timestamp_msg']

No valid af mask found for 2023-11-04 09:10:00
No valid af mask found for 2023-11-05 06:38:00
No valid af mask found for 2023-12-04 14:32:00
No matching af mask found for 2023-03-13 12:58:00
No valid af mask found for 2023-11-08 09:00:00
No valid af mask found for 2023-10-13 09:55:00
No matching af mask found for 2023-04-27 10:00:00
No valid af mask found for 2023-10-02 16:49:00
No matching af mask found for 2023-04-21 10:27:00
No valid af mask found for 2023-11-02 10:00:00
No matching af mask found for 2023-03-17 13:18:00
No matching af mask found for 2023-03-27 14:45:00
No matching af mask found for 2023-03-13 11:46:00
No valid af mask found for 2023-11-03 10:36:00
No matching af mask found for 2023-04-07 08:00:00
No matching af mask found for 2023-03-31 13:00:00
No valid af mask found for 2023-10-11 17:38:00
No valid af mask found for 2023-10-21 07:00:00
No matching af mask found for 2023-02-06 11:17:00
No matching af mask found for 2023-03-25 14:16:00
No valid af mask found for 2023-10-05 11:08:00
No matching af mask found for 2023-02-18 10:35:00
No matching af mask found for 2023-02-25 12:05:00
No matching af mask found for 2023-03-18 09:03:00
No valid af mask found for 2023-11-17 14:10:00
No matching af mask found for 2023-01-03 17:16:00
No valid af mask found for 2023-10-11 13:05:00
No matching af mask found for 2023-03-31 17:50:00
No matching af mask found for 2023-03-30 14:05:00
No valid af mask found for 2023-12-24 20:10:00
No valid af mask found for 2023-10-26 21:36:00
No matching af mask found for 2023-02-12 10:25:00
No valid af mask found for 2023-10-04 10:30:00
No matching af mask found for 2023-02-25 13:00:00
No matching af mask found for 2023-02-27 08:03:00
No matching af mask found for 2023-03-25 13:40:00
No matching af mask found for 2023-01-19 12:28:00
No matching af mask found for 2023-02-21 15:25:00
No valid af mask found for 2023-12-02 08:13:00
No valid af mask found for 2023-12-24 12:55:00
No valid af mask found for 2023-10-15 11:44:00
No matching af mask found for 2023-01-06 13:30:00
No valid af mask found for 2023-12-28 09:11:00
No matching af mask found for 2023-03-17 15:00:00
No valid af mask found for 2023-10-20 11:15:00
No matching af mask found for 2023-03-26 10:14:00
No valid af mask found for 2023-11-12 10:52:00
No matching af mask found for 2023-01-06 03:49:00
No matching af mask found for 2023-01-08 09:59:00
No matching af mask found for 2023-02-20 10:19:00
No valid af mask found for 2023-10-09 10:03:00
No valid af mask found for 2023-10-09 07:40:00
No valid af mask found for 2023-10-02 17:25:00
No valid af mask found for 2023-12-18 13:31:00
No matching af mask found for 2023-02-26 06:47:00
No valid af mask found for 2023-11-07 09:28:00
No valid af mask found for 2023-10-25 16:24:00
No valid af mask found for 2023-10-12 14:42:00
No valid af mask found for 2023-10-28 11:30:00
No valid af mask found for 2023-10-31 10:51:00
No valid af mask found for 2023-10-16 15:30:00
No matching af mask found for 2023-02-25 16:40:00
No valid af mask found for 2023-10-31 10:23:00
No valid af mask found for 2023-10-31 11:13:00
No matching af mask found for 2023-02-20 13:34:00
No valid af mask found for 2023-11-25 03:26:00
No valid af mask found for 2023-11-07 13:19:00
No valid af mask found for 2023-10-11 16:07:00
No valid af mask found for 2023-10-03 08:43:00
No matching af mask found for 2023-03-26 16:15:00
No matching af mask found for 2023-02-20 12:34:00
No matching af mask found for 2023-03-24 08:22:00
No matching af mask found for 2023-02-27 09:30:00
No valid af mask found for 2023-11-04 08:26:00
No matching af mask found for 2023-04-03 10:20:00
No matching af mask found for 2023-04-13 13:10:00
No matching af mask found for 2023-02-27 17:00:00
No valid af mask found for 2023-10-16 08:40:00
No matching af mask found for 2023-04-28 13:00:00
No valid af mask found for 2023-11-08 10:40:00
No matching af mask found for 2023-02-26 10:15:00
No matching af mask found for 2023-03-03 16:22:00
No valid af mask found for 2023-11-19 12:06:00
No matching af mask found for 2023-03-24 15:20:00
No matching af mask found for 2023-03-31 15:56:00
No matching af mask found for 2023-02-20 18:02:00
No matching af mask found for 2023-02-20 10:34:00
No matching af mask found for 2023-02-08 12:19:00
No matching af mask found for 2023-02-10 16:10:00
No valid af mask found for 2023-12-19 12:14:00
No valid af mask found for 2023-11-17 16:30:00
No valid af mask found for 2023-11-01 16:10:00
No matching af mask found for 2023-02-25 20:47:00
No valid af mask found for 2023-10-23 10:23:00
No matching af mask found for 2023-02-22 13:08:00
No valid af mask found for 2023-10-16 12:36:00
No matching af mask found for 2023-03-30 12:14:00
No matching af mask found for 2023-02-24 12:10:00
No valid af mask found for 2023-11-25 10:32:00
No matching af mask found for 2023-02-18 10:30:00
No valid af mask found for 2023-10-31 15:02:00
No matching af mask found for 2023-03-27 14:40:00
No matching af mask found for 2023-03-12 16:01:00
No valid af mask found for 2023-10-09 12:48:00
No matching af mask found for 2023-02-13 09:36:00
No valid af mask found for 2023-11-04 10:04:00
No valid af mask found for 2023-12-28 13:32:00
No valid af mask found for 2023-10-02 16:43:00
No valid af mask found for 2023-12-28 12:30:00
No matching af mask found for 2023-04-28 12:23:00
No matching af mask found for 2023-02-02 12:30:00
No valid af mask found for 2023-10-25 15:09:00
No matching af mask found for 2023-03-10 09:14:00
No valid af mask found for 2023-10-09 10:50:00
No valid af mask found for 2023-10-12 15:45:00
No valid af mask found for 2023-11-08 18:00:00
No valid af mask found for 2023-11-08 18:30:00
No matching af mask found for 2023-02-25 09:05:00
No valid af mask found for 2023-11-07 12:00:00
No valid af mask found for 2023-11-06 12:30:00
No valid af mask found for 2023-10-02 06:50:00
No matching af mask found for 2023-03-08 14:29:00
No matching af mask found for 2023-04-14 16:20:00
No valid af mask found for 2023-11-20 09:08:00
No valid af mask found for 2023-10-02 13:00:00
No matching af mask found for 2023-03-17 15:42:00
No matching af mask found for 2023-03-26 13:59:00
No matching af mask found for 2023-04-18 16:05:00
No matching af mask found for 2023-01-09 15:45:00
No valid af mask found for 2023-10-12 12:50:00
No matching af mask found for 2023-02-20 09:50:00
No valid af mask found for 2023-10-22 10:31:00
No valid af mask found for 2023-11-05 19:53:00
No valid af mask found for 2023-10-16 12:40:00
No matching af mask found for 2023-02-18 14:49:00
No matching af mask found for 2023-02-26 11:53:00
No valid af mask found for 2023-11-06 12:24:00
No matching af mask found for 2023-03-28 00:00:00
No matching af mask found for 2023-03-30 17:00:00
No matching af mask found for 2023-03-31 13:45:00
No valid af mask found for 2023-11-08 17:18:00
No matching af mask found for 2023-04-27 13:05:00
No valid af mask found for 2023-11-07 12:49:00
No matching af mask found for 2023-02-20 14:59:00
No matching af mask found for 2023-02-18 10:14:00
No matching af mask found for 2023-01-22 15:30:00
No valid af mask found for 2023-11-01 15:00:00
No matching af mask found for 2023-02-15 09:15:00
No valid af mask found for 2023-10-09 11:33:00
No valid af mask found for 2023-11-10 16:59:00
No valid af mask found for 2023-10-12 11:04:00
No valid af mask found for 2023-10-14 20:59:00
No matching af mask found for 2023-03-13 14:50:00
No matching af mask found for 2023-02-04 12:30:00
No matching af mask found for 2023-02-25 10:25:00
No matching af mask found for 2023-02-10 17:15:00
No matching af mask found for 2023-02-10 11:08:00
No matching af mask found for 2023-03-29 13:03:00
No matching af mask found for 2023-02-11 12:30:00
No matching af mask found for 2023-01-08 11:44:00
No matching af mask found for 2023-03-19 11:52:00
No valid af mask found for 2023-10-11 10:07:00
No matching af mask found for 2023-02-16 14:00:00
No valid af mask found for 2023-10-30 11:30:00
No matching af mask found for 2023-03-30 15:00:00
No valid af mask found for 2023-10-07 10:39:00
No matching af mask found for 2023-03-30 08:35:00
No matching af mask found for 2023-02-26 14:15:00
No valid af mask found for 2023-10-21 11:15:00
No matching af mask found for 2023-04-01 11:06:00
No valid af mask found for 2023-10-14 12:34:00
No valid af mask found for 2023-11-17 13:25:00
No valid af mask found for 2023-11-22 07:54:00
No valid af mask found for 2023-10-31 11:03:00
No matching af mask found for 2023-04-01 12:40:00
No matching af mask found for 2023-02-26 09:20:00
No matching af mask found for 2023-01-18 15:05:00
No valid af mask found for 2023-10-25 10:40:00
No matching af mask found for 2023-03-27 11:31:00
No valid af mask found for 2023-11-04 01:34:00
No matching af mask found for 2023-02-26 12:55:00
No matching af mask found for 2023-04-02 13:34:00
No matching af mask found for 2023-02-19 10:12:00
No valid af mask found for 2023-10-21 14:19:00
No valid af mask found for 2023-10-08 14:00:00
No matching af mask found for 2023-02-14 11:56:00
No valid af mask found for 2023-10-29 16:03:00
No valid af mask found for 2023-11-01 14:07:00
No valid af mask found for 2023-11-08 17:12:00
No valid af mask found for 2023-11-12 15:27:00
No matching af mask found for 2023-02-06 12:10:00
No valid af mask found for 2023-10-05 13:00:00
No matching af mask found for 2023-03-14 14:10:00
No valid af mask found for 2023-10-08 15:50:00
No matching af mask found for 2023-03-14 14:22:00
No matching af mask found for 2023-02-20 16:18:00
No valid af mask found for 2023-10-02 07:05:00
No matching af mask found for 2023-03-12 06:11:00
No valid af mask found for 2023-10-05 13:30:00
No matching af mask found for 2023-02-20 08:51:00
No valid af mask found for 2023-10-14 16:09:00
No valid af mask found for 2023-10-16 11:01:00
No matching af mask found for 2023-04-01 07:00:00
No valid af mask found for 2023-11-05 12:26:00
No valid af mask found for 2023-11-01 15:15:00
No valid af mask found for 2023-11-04 17:32:00
No matching af mask found for 2023-02-24 17:23:00
No matching af mask found for 2023-04-11 19:25:00
No valid af mask found for 2023-11-01 12:10:00
No matching af mask found for 2023-02-18 14:51:00
No valid af mask found for 2023-10-26 16:21:00
No matching af mask found for 2023-02-26 08:09:00
No matching af mask found for 2023-03-25 11:03:00
No valid af mask found for 2023-10-25 16:13:00
No valid af mask found for 2023-10-20 11:10:00
No valid af mask found for 2023-10-22 10:30:00
No valid af mask found for 2023-10-23 14:55:00
No matching af mask found for 2023-04-02 12:55:00
No valid af mask found for 2023-10-30 13:20:00
No valid af mask found for 2023-10-13 11:36:00
No valid af mask found for 2023-10-04 09:08:00
No matching af mask found for 2023-02-19 14:35:00
No valid af mask found for 2023-10-11 14:00:00
No matching af mask found for 2023-02-25 09:21:00
No matching af mask found for 2023-02-26 12:15:00
No valid af mask found for 2023-10-01 16:30:00
No valid af mask found for 2023-12-31 14:45:00
No matching af mask found for 2023-03-03 09:33:00
No matching af mask found for 2023-04-01 12:53:00
No valid af mask found for 2023-10-17 16:30:00
No valid af mask found for 2023-10-31 13:10:00
No valid af mask found for 2023-10-07 13:05:00
No matching af mask found for 2023-03-01 15:40:00
No valid af mask found for 2023-11-20 11:49:00
No valid af mask found for 2023-12-23 14:43:00
No valid af mask found for 2023-10-10 13:40:00
No valid af mask found for 2023-10-11 07:00:00
No valid af mask found for 2023-10-03 16:00:00
No matching af mask found for 2023-02-17 15:53:00
No valid af mask found for 2023-10-09 09:24:00
No valid af mask found for 2023-11-16 09:54:00
No matching af mask found for 2023-04-07 06:17:00
No matching af mask found for 2023-03-30 14:15:00
No valid af mask found for 2023-11-03 12:35:00
No valid af mask found for 2023-10-30 10:20:00
No valid af mask found for 2023-12-07 08:17:00
No matching af mask found for 2023-02-25 14:50:00
No valid af mask found for 2023-10-04 16:35:00
No matching af mask found for 2023-01-30 10:00:00
No valid af mask found for 2023-10-22 12:10:00
No matching af mask found for 2023-02-26 08:25:00
No matching af mask found for 2023-02-18 14:04:00
No valid af mask found for 2023-10-08 10:35:00
No matching af mask found for 2023-02-20 13:48:00
No valid af mask found for 2023-12-06 09:09:00
No matching af mask found for 2023-04-13 14:30:00
No matching af mask found for 2023-03-09 15:23:00
No matching af mask found for 2023-02-17 09:48:00
No valid af mask found for 2023-10-12 07:12:00
No matching af mask found for 2023-03-30 16:45:00
No matching af mask found for 2023-02-09 09:16:00
No matching af mask found for 2023-03-30 11:25:00
No matching af mask found for 2023-01-19 13:49:00
No matching af mask found for 2023-02-20 12:22:00
No matching af mask found for 2023-02-24 12:54:00
No valid af mask found for 2023-10-30 14:16:00
No valid af mask found for 2023-10-25 11:15:00
No valid af mask found for 2023-10-24 13:40:00
No matching af mask found for 2023-02-07 15:05:00
No valid af mask found for 2023-10-08 11:27:00
No matching af mask found for 2023-01-06 14:30:00
No matching af mask found for 2023-04-27 18:22:00
No valid af mask found for 2023-10-11 20:00:00
No valid af mask found for 2023-10-11 12:10:00
No matching af mask found for 2023-04-08 02:24:00
No valid af mask found for 2023-10-25 16:11:00
No valid af mask found for 2023-10-04 09:30:00
No matching af mask found for 2023-02-04 12:18:00
No valid af mask found for 2023-11-06 10:54:00
No valid af mask found for 2023-10-09 13:10:00
No matching af mask found for 2023-04-19 11:42:00
No matching af mask found for 2023-02-13 11:03:00
No matching af mask found for 2023-01-18 10:30:00
No valid af mask found for 2023-10-31 11:08:00
No valid af mask found for 2023-10-01 08:20:00
No valid af mask found for 2023-10-29 08:50:00
No valid af mask found for 2023-10-25 17:43:00
No valid af mask found for 2023-10-03 08:27:00
No valid af mask found for 2023-10-15 17:56:00
No valid af mask found for 2023-12-27 23:30:00
No matching af mask found for 2023-02-26 18:00:00
No matching af mask found for 2023-02-22 11:31:00
No matching af mask found for 2023-01-09 14:41:00
No valid af mask found for 2023-10-08 08:05:00
No matching af mask found for 2023-02-18 12:41:00
No valid af mask found for 2023-10-05 14:50:00
No valid af mask found for 2023-11-21 10:30:00
No matching af mask found for 2023-01-27 11:42:00
No matching af mask found for 2023-01-19 11:05:00
No matching af mask found for 2023-02-24 13:15:00
No valid af mask found for 2023-12-04 15:08:00
No valid af mask found for 2023-10-21 09:40:00
No matching af mask found for 2023-03-27 13:36:00
No matching af mask found for 2023-03-09 15:26:00
No valid af mask found for 2023-11-03 09:25:00
No matching af mask found for 2023-02-26 10:30:00
No valid af mask found for 2023-11-20 13:10:00
No valid af mask found for 2023-10-16 07:24:00
No matching af mask found for 2023-02-20 10:36:00
No valid af mask found for 2023-12-26 09:48:00
No valid af mask found for 2023-10-23 13:40:00
No valid af mask found for 2023-10-14 11:59:00
No valid af mask found for 2023-11-06 09:44:00
No matching af mask found for 2023-03-27 14:18:00
No valid af mask found for 2023-10-15 12:57:00
No valid af mask found for 2023-11-28 14:42:00
No matching af mask found for 2023-03-03 10:37:00
No valid af mask found for 2023-11-18 10:09:00
No matching af mask found for 2023-02-28 13:16:00
No matching af mask found for 2023-03-27 17:15:00
No valid af mask found for 2023-11-21 05:28:00
No matching af mask found for 2023-02-18 13:55:00
No valid af mask found for 2023-10-06 08:55:00
No matching af mask found for 2023-02-19 09:20:00
No matching af mask found for 2023-03-20 10:57:00
No valid af mask found for 2023-11-01 11:45:00
No matching af mask found for 2023-03-14 14:27:00
No valid af mask found for 2023-10-07 07:09:00
No valid af mask found for 2023-11-04 11:02:00
No matching af mask found for 2023-04-05 18:26:00
No matching af mask found for 2023-01-04 11:05:00
No matching af mask found for 2023-02-22 15:30:00
No valid af mask found for 2023-11-09 11:50:00
No matching af mask found for 2023-02-21 11:59:00
No valid af mask found for 2023-10-08 14:35:00
No matching af mask found for 2023-02-21 07:17:00
No matching af mask found for 2023-02-26 08:40:00
No matching af mask found for 2023-04-01 13:28:00
No valid af mask found for 2023-11-17 12:28:00
No valid af mask found for 2023-10-06 16:00:00
No matching af mask found for 2023-03-14 14:44:00
No valid af mask found for 2023-10-07 02:29:00
No matching af mask found for 2023-02-16 07:55:00
No valid af mask found for 2023-10-11 13:36:00
No valid af mask found for 2023-10-03 16:59:00
No matching af mask found for 2023-03-29 09:52:00
No valid af mask found for 2023-11-20 11:55:00
No matching af mask found for 2023-02-26 12:31:00
No matching af mask found for 2023-02-24 18:35:00
No matching af mask found for 2023-03-27 13:32:00
No valid af mask found for 2023-10-25 17:40:00
No valid af mask found for 2023-11-25 14:45:00
No valid af mask found for 2023-11-16 11:57:00
No matching af mask found for 2023-03-29 14:08:00
No matching af mask found for 2023-03-27 14:21:00
No valid af mask found for 2023-11-03 10:38:00
No matching af mask found for 2023-03-26 11:15:00
No valid af mask found for 2023-12-23 14:35:00
No matching af mask found for 2023-03-13 07:33:00
No valid af mask found for 2023-10-10 10:29:00

In [15]:
df_matches

       timestamp_fb   timestamp_msg
0    20230821100500  20230821101241
1    20230718160900  20230718161242
2    20230819014000  20230819014242
3    20230717140800  20230717141241
4    20230726103500  20230726104241
..              ...             ...
497  20230816105800  20230816111241
498  20230804152100  20230804152741
499  20230806141200  20230806141241
500  20230829112200  20230829112742
501  20230605124900  20230605125741

[502 rows x 2 columns]

In [14]:
timestamp_msg = '20230821095741'

In [16]:
def find_next_msg_files(timestamp_msg, steps=3):
    timestamp_msg_dt = datetime.strptime(timestamp_msg, "%Y%m%d%H%M%S")
    timestamps = [timestamp_msg_dt + timedelta(minutes=15 * i) for i in range(1, steps + 1)]
    timestamp_strings = [dt.strftime("%Y%m%d%H%M") for dt in timestamps]
    datasets = [os.path.join(msg_path, f"{timestamp_msg}_msg.nc")]
    for ts in timestamp_strings:
        file_pattern = os.path.join(msg_path, f"{ts}*_msg.nc")  # Match files without seconds
        files = glob.glob(file_pattern)
        if len(files) > 0:
            datasets.append(files[0])
    return datasets

In [18]:
def af_patch_from_msg(msg, y_idx, x_idx, random_n_x, random_n_y):
    array = np.zeros((msg.y.size, msg.x.size))
    array[y_idx, x_idx] = 1
    da = xr.DataArray(
        array,
        coords={"y": msg.y, "x": msg.x},
        dims=("y", "x")
    )
    da_sel = da.isel(x=slice(x_idx - random_n_x, x_idx + (32 - random_n_x)), y = slice(y_idx - random_n_y, y_idx + (32 - random_n_y)))
    return da_sel

In [19]:
def create_msg_af_patches(msg, crs, lat, lon, itime, step):
    x, y = convert_lat_lon_to_x_y(crs, lon, lat)
    selected = msg.sel(x=x, y=y, method='nearest')
    # Get the indices of the nearest point
    x_idx = msg.get_index('x').get_loc(selected['x'].item())
    y_idx = msg.get_index('y').get_loc(selected['y'].item())
    for i in range(1, 3):
        random_n_x = np.random.randint(4, 28)
        random_n_y = np.random.randint(4, 28)
        msg_sel = msg.isel(x=slice(x_idx - random_n_x, x_idx + (32 - random_n_x)), y = slice(y_idx - random_n_y, y_idx + (32 - random_n_y)))
        # concatenate variables
        msg_sel_temp = xr.concat(
            [msg_sel.cloud_mask, msg_sel.latitude, msg_sel.longitude], dim="band"
        )
        # name data variables "Rad"
        msg_sel_temp = msg_sel_temp.to_dataset(name="Rad")
        msg_sel_temp = msg_sel_temp.drop_vars(["cloud_mask", "latitude", "longitude"])
        msg_sel_temp = msg_sel_temp.assign_coords(
            band=["cloud_mask", "latitude", "longitude"]
        )
        # merge with original dataset
        ds = xr.merge([msg_sel_temp.Rad, msg_sel.Rad])
        # store band names to be attached to da later
        band_names = [str(i) for i in ds.band.values]
        del msg_sel_temp
        gc.collect()

        # extract radiance data array
        da = ds.Rad
        da.attrs["fb_datetime"] = str('test')
        da.attrs["msg_time"] = msg.time.values[0]
        da.attrs["step"] = step
        da_af = af_patch_from_msg(msg, y_idx, x_idx, random_n_x, random_n_y)
        file_path_msg = Path(save_msg_path).joinpath(
                        f"{itime}_patch_5000_v{i}_dt{step}.tif"
                )
                # remove file if it already exists
        if os.path.exists(file_path_msg):
            os.remove(file_path_msg)
        da.rio.to_raster(file_path_msg)
        file_path_af = Path(save_af_path).joinpath(
                        f"{itime}_patch_5000_v{i}_dt{step}.tif"
                )
                # remove file if it already exists
        if os.path.exists(file_path_af):
            os.remove(file_path_af)
        da_af.rio.to_raster(file_path_af)

In [22]:
for index, row in df_matches.iterrows():
    timestamp_fb = row['timestamp_fb']
    timestamp_msg = row['timestamp_msg']
    lat = fd_sub[fd_sub.timestamp_ut_str == timestamp_fb]['Y-ENGAGE'].values
    lon = fd_sub[fd_sub.timestamp_ut_str == timestamp_fb]['X-ENGAGE'].values
    images_msg = find_next_msg_files(timestamp_msg, steps = 3)
    for n_dt, tm_msg in enumerate(images_msg):
        print(f'Processing {n_dt}, {tm_msg}')
        msg = xr.open_dataset(os.path.join(msg_path, tm_msg))
        var = "msg_seviri_fes_3km"
        crs_wkt = msg[var].crs_wkt
        crs = CRS(crs_wkt)
        try:
            create_msg_af_patches(msg, crs, lat, lon, timestamp_msg , step = n_dt)
        except:
            print(f'Error in processing msg {timestamp_msg} and af {timestamp_fb}')

Processing 0, /mnt/outputs/geoprocessed/20230821101241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230821102741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230821104241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230821105741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230718161242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230718162742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230718164241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230718165741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230819014242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230819015742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230819021242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230819022742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230717141241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230717142741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230717144242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230717145742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230726104241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230726105741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230726111242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230726112742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230822091242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230822092741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230822095741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230821061242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230821062742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230821064242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230821065741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230717092741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230717095741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230717101241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230823115741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230823121242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230823122741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230823124241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230821145742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230821151242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230821152742_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230821154242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230723145742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230723151242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230723152741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230723154241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230821112742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230821114242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230821115742_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230821121241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230723094242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230723095742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230723102742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230723125741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230723131242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230723132742_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230723134241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230821104241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230821105741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230821111242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230821112742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230717114242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230717115742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230717121242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230717122741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230822102742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230822105741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230822111241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230714094241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230714095741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230714101241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230821131242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230821132742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230821134241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230821135741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230821071241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230821072741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230821074242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230821075742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230826071241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230826072741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230826074242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230826075742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230723102742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230723104241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230723105741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230723111242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230702142741_msg.nc
Error in processing msg 20230702142741 and af 20230702142700
Processing 1, /mnt/outputs/geoprocessed/20230702144241_msg.nc
Error in processing msg 20230702142741 and af 20230702142700
Processing 2, /mnt/outputs/geoprocessed/20230702145741_msg.nc
Error in processing msg 20230702142741 and af 20230702142700
Processing 3, /mnt/outputs/geoprocessed/20230702151242_msg.nc
Error in processing msg 20230702142741 and af 20230702142700
Processing 0, /mnt/outputs/geoprocessed/20230822102742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230822105741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230822111241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230726125741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230726131242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230726132742_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230726134241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230719115742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230719121241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230719122741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230719124241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230821091241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230821092742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230821094242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230821095741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230822105741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230822111241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230822114241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230822134242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230822135742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230822141242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230822142742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230818124242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230818125741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230818131241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230818132741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230822092741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230822095741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230706171242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230706172741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230706174241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230706175741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230726144242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230726145742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230726151241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230726152741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230903172741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230903174242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230903175742_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230903181241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230824124241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230824131241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230824132741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230701115742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230701121242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230701122741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230701124241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230726121241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230726122741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230726124241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230726125741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230830114242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230830115742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230830121241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230830122741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230831101241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230831102741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230831104242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230831105742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230730182742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230730185742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230730191242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230822111241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230822114241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230822115741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230717111241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230717112742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230717114242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230717115742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230806102742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230806104242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230806105742_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230806111241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230630114242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230630115742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230630121241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230630122741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230727154242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230727155742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230727162741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230920094242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230920095742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230920101241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230808091242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230808092742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230808094241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230808095741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230727131241_msg.nc
Error in processing msg 20230727131241 and af 20230727130000
Processing 1, /mnt/outputs/geoprocessed/20230727134242_msg.nc
Error in processing msg 20230727131241 and af 20230727130000
Processing 2, /mnt/outputs/geoprocessed/20230727135742_msg.nc
Error in processing msg 20230727131241 and af 20230727130000
Processing 0, /mnt/outputs/geoprocessed/20230723132742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230723134241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230723135741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230723141241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230726111242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230726112742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230726114242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230726115742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230813182741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230813184241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230813185741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230813191242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230907124241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230907125741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230907131242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230907132742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230821075742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230821081242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230821082741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230821084241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230825165741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230825171241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230825172742_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230825174242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230805151242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230805152742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230805154241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230805155741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230726102742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230726104241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230726105741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230726111242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230812231242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230812232741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230812234241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230812235741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230808124241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230808125741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230808131242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230808132742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230722105741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230722111242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230722112742_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230722114242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230826141241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230826142742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230826144242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230826145742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230802145742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230802151242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230802152742_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230802154241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230707151242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230707152742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230707154242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230819112741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230819114241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230819115741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230819121242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230609085742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230609091242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230609092741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230609094241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230723141241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230723142741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230723144242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230723145742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230913124241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230913125741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230913131241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230913132742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230808104242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230808105742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230808111241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230808112741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230908191242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230908192742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230908194241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230908195741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230715094241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230715095741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230715101241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230715102742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230715162742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230715164242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230715165742_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230715171241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230822195741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230822201241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230822202741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230930104242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230930105742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230930111241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230930112741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230824131241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230824132741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230824134242_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230824135742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230804104242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230804105741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230804112742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230630101242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230630102741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230630104241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230630105741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230825094242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230825101242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230825102741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230726211242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230726212741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230726214241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230726215741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230712075741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230712081241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230712082741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230712084242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230704141242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230704144241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230704145741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230826095742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230826101242_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230826104241_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230819184241_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230819185741_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230819191241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230819192742_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230726132742_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230726134241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230726135741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230726141242_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230920111242_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230920112742_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230920114241_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230920115741_msg.nc
Processing 0, /mnt/outputs/geoprocessed/20230706105741_msg.nc
Processing 1, /mnt/outputs/geoprocessed/20230706111241_msg.nc
Processing 2, /mnt/outputs/geoprocessed/20230706112741_msg.nc
Processing 3, /mnt/outputs/geoprocessed/20230706114242_msg.nc

In [41]:
#read tif files with rioxarray
import rasterio

test = rioxarray.open_rasterio('/mnt/data8tb/fire_detection/fire_brigade/20230821101241_patch_5000_v2_st3.tif')

In [42]:
test

<xarray.DataArray (band: 14, y: 32, x: 32)> Size: 115kB
[14336 values with dtype=float64]
Coordinates:
  * band         (band) int64 112B 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * x            (x) float64 256B 1.95e+06 1.953e+06 ... 2.04e+06 2.043e+06
  * y            (y) float64 256B 3.886e+06 3.889e+06 ... 3.976e+06 3.979e+06
    spatial_ref  int64 8B 0
Attributes:
    fb_datetime:   test
    msg_time:      2023-08-21 10:45:00
    step:          3
    scale_factor:  1.0
    add_offset:    0.0
    long_name:     Rad