In [17]:
import xarray as xr
import autoroot
from satpy.scene import Scene
from pyhdf.SD import SD, SDC 
import pandas as pd
import cartopy.crs as ccrs
from pyproj import CRS, Transformer
import rioxarray
import numpy as np
import matplotlib.pyplot as plt
from pyresample import create_area_def
import os
from rs_tools._src.geoprocessing.match import match_timestamps_af
from rs_tools._src.utils.io import get_list_filenames
from pathlib import Path
from utils_msg_modis_aligment import parse_af_dates_from_file, reproject_msg_image, clip_and_align, check_overlap

In [18]:
modis_cm_path =  '/mnt/data8tb/fire_detection/modis/CM'
files = [os.path.join(modis_cm_path, i) for i in os.listdir(modis_cm_path) if i.endswith('.hdf')]
print(f"Found {len(files)} MODIS files")

outpath = '/mnt/data8tb/fire_detection/modis/msg_cm_dataset'

Found 4716 MODIS files

In [19]:
modis_cm_path = '/mnt/data8tb/fire_detection/modis/CM'
seviri_path = "/mnt/seviri/geoprocessed"

#/mnt/outputs/geoprocessed

In [20]:
cm_files = [ i for i in os.listdir(modis_cm_path) if i.endswith('.tif')]
cm_df = pd.DataFrame({'name': cm_files})

In [21]:
cm_df

                                              name
0     MYD35_L2.A2024167.1405.061.2024168152141.tif
1     MYD35_L2.A2022263.1220.061.2022264194231.tif
2     MYD35_L2.A2020195.1015.061.2020196155024.tif
3     MYD35_L2.A2020187.1100.061.2020188144050.tif
4     MYD35_L2.A2021190.1150.061.2021191152816.tif
...                                            ...
4711  MYD35_L2.A2020214.1225.061.2020215151145.tif
4712  MYD35_L2.A2024154.1005.061.2024156170958.tif
4713  MYD35_L2.A2021262.0920.061.2021262192707.tif
4714  MYD35_L2.A2021186.0855.061.2021186194104.tif
4715  MYD35_L2.A2023214.0915.061.2023214192714.tif

[4716 rows x 1 columns]

In [22]:
pat = r'\.A(?P<y>\d{4})(?P<doy>\d{3})\.(?P<hh>\d{2})(?P<mm>\d{2})'
parts = cm_df['name'].str.extract(pat)
# to numeric
parts = parts.apply(pd.to_numeric, errors='coerce')
cm_df['datetime'] = (
    pd.to_datetime(parts['y'], format='%Y')
    + pd.to_timedelta(parts['doy'] - 1, unit='D')
    + pd.to_timedelta(parts['hh'], unit='h')
    + pd.to_timedelta(parts['mm'], unit='m')
)
cm_df['utimes'] = cm_df['datetime'].dt.strftime('%Y%m%d%H%M00')
unique_times_cm = cm_df['datetime'].dt.strftime('%Y%m%d%H%M00').unique().tolist()

In [23]:
cm_df

,name,datetime,utimes
0,MYD35_L2.A2024167.1405.061.2024168152141.tif,2024-06-15 14:05:00,20240615140500
1,MYD35_L2.A2022263.1220.061.2022264194231.tif,2022-09-20 12:20:00,20220920122000
2,MYD35_L2.A2020195.1015.061.2020196155024.tif,2020-07-13 10:15:00,20200713101500
3,MYD35_L2.A2020187.1100.061.2020188144050.tif,2020-07-05 11:00:00,20200705110000
4,MYD35_L2.A2021190.1150.061.2021191152816.tif,2021-07-09 11:50:00,20210709115000
...,...,...,...
4711,MYD35_L2.A2020214.1225.061.2020215151145.tif,2020-08-01 12:25:00,20200801122500
4712,MYD35_L2.A2024154.1005.061.2024156170958.tif,2024-06-02 10:05:00,20240602100500
4713,MYD35_L2.A2021262.0920.061.2021262192707.tif,2021-09-19 09:20:00,20210919092000
4714,MYD35_L2.A2021186.0855.061.2021186194104.tif,2021-07-05 08:55:00,20210705085500
4715,MYD35_L2.A2023214.0915.061.2023214192714.tif,2023-08-02 09:15:00,20230802091500

In [24]:
files_msg = get_list_filenames(seviri_path, ".nc")

In [25]:
unique_times_msg = list(set(map(parse_af_dates_from_file, files_msg)))

In [26]:
df_matches = match_timestamps_af(unique_times_cm, unique_times_msg, cutoff=15)
df_matches.columns = ['timestamp_cm', 'timestamp_msg']

No valid af mask found for 2024-06-15 14:05:00
No matching af mask found for 2022-09-20 12:20:00
No matching af mask found for 2020-07-13 10:15:00
No matching af mask found for 2020-07-05 11:00:00
No matching af mask found for 2021-07-09 11:50:00
No matching af mask found for 2023-09-11 09:25:00
No matching af mask found for 2021-06-04 09:35:00
No matching af mask found for 2021-08-25 14:20:00
No matching af mask found for 2020-09-23 14:25:00
No matching af mask found for 2020-09-14 11:10:00
No matching af mask found for 2022-07-23 14:30:00
No matching af mask found for 2021-07-27 11:40:00
No matching af mask found for 2022-06-07 11:05:00
No matching af mask found for 2022-09-25 12:30:00
No matching af mask found for 2023-07-06 10:00:00
No matching af mask found for 2022-07-01 13:35:00
No matching af mask found for 2022-07-05 09:45:00
No valid af mask found for 2024-07-15 13:05:00
No matching af mask found for 2022-09-27 14:00:00
No matching af mask found for 2021-09-25 10:20:00
No matching af mask found for 2022-09-23 12:45:00
No valid af mask found for 2024-08-12 12:25:00
No matching af mask found for 2021-06-19 10:40:00
No valid af mask found for 2024-07-03 11:30:00
No matching af mask found for 2022-08-29 09:45:00
No matching af mask found for 2023-08-05 09:40:00
No matching af mask found for 2020-06-05 09:20:00
No matching af mask found for 2021-06-01 14:05:00
No matching af mask found for 2020-06-09 13:50:00
No matching af mask found for 2020-07-10 09:45:00
No matching af mask found for 2022-09-21 12:55:00
No matching af mask found for 2023-06-16 12:20:00
No matching af mask found for 2020-07-18 10:35:00
No matching af mask found for 2023-07-13 13:15:00
No matching af mask found for 2022-06-11 10:40:00
No matching af mask found for 2021-08-11 12:35:00
No valid af mask found for 2024-08-24 12:20:00
No matching af mask found for 2022-08-18 11:45:00
No matching af mask found for 2023-06-23 10:50:00
No matching af mask found for 2020-07-06 10:05:00
No matching af mask found for 2020-08-24 12:35:00
No matching af mask found for 2022-07-31 11:55:00
No matching af mask found for 2023-07-12 14:15:00
No matching af mask found for 2022-06-19 09:55:00
No valid af mask found for 2024-09-17 10:25:00
No matching af mask found for 2021-08-30 13:00:00
No matching af mask found for 2023-09-12 11:45:00
No valid af mask found for 2023-09-29 12:00:00
No matching af mask found for 2023-09-03 13:35:00
No matching af mask found for 2021-09-27 10:10:00
No matching af mask found for 2022-09-04 12:25:00
No valid af mask found for 2024-07-07 11:00:00
No matching af mask found for 2020-09-30 09:35:00
No matching af mask found for 2020-06-22 13:15:00
No matching af mask found for 2022-07-07 11:10:00
No matching af mask found for 2022-09-14 12:50:00
No matching af mask found for 2020-06-15 13:10:00
No matching af mask found for 2023-08-31 13:05:00
No matching af mask found for 2021-07-26 14:10:00
No matching af mask found for 2020-07-09 10:45:00
No matching af mask found for 2020-07-04 12:00:00
No matching af mask found for 2023-07-29 11:25:00
No valid af mask found for 2024-09-21 09:55:00
No matching af mask found for 2021-09-20 10:05:00
No matching af mask found for 2021-06-10 13:55:00
No valid af mask found for 2024-09-23 14:30:00
No matching af mask found for 2022-06-16 11:00:00
No matching af mask found for 2023-07-31 09:35:00
No matching af mask found for 2021-09-01 12:50:00
No matching af mask found for 2022-07-11 09:15:00
No matching af mask found for 2021-08-13 10:45:00
No matching af mask found for 2022-09-18 09:10:00
No matching af mask found for 2023-09-05 10:00:00
No matching af mask found for 2021-06-02 11:30:00
No valid af mask found for 2024-07-29 11:10:00
No matching af mask found for 2022-06-30 11:10:00
No matching af mask found for 2021-09-17 14:30:00
No matching af mask found for 2021-09-20 11:45:00
No matching af mask found for 2023-07-18 10:15:00
No matching af mask found for 2022-09-07 14:30:00
No valid af mask found for 2024-06-14 15:05:00
No matching af mask found for 2020-08-09 13:10:00
No matching af mask found for 2022-09-01 13:25:00
No valid af mask found for 2024-08-22 12:40:00
No matching af mask found for 2023-08-01 13:30:00
No matching af mask found for 2022-06-06 13:45:00
No matching af mask found for 2021-06-02 09:55:00
No valid af mask found for 2023-09-24 11:50:00
No matching af mask found for 2020-09-11 13:55:00
No matching af mask found for 2023-06-12 14:30:00
No matching af mask found for 2020-09-07 14:20:00
No matching af mask found for 2021-07-20 09:50:00
No matching af mask found for 2022-09-29 10:25:00
No valid af mask found for 2024-08-30 13:05:00
No matching af mask found for 2020-09-24 13:30:00
No matching af mask found for 2020-08-17 10:50:00
No matching af mask found for 2020-07-11 13:45:00
No matching af mask found for 2023-08-13 10:20:00
No matching af mask found for 2021-06-11 11:20:00
No matching af mask found for 2023-07-04 11:55:00
No matching af mask found for 2020-09-29 12:10:00
No valid af mask found for 2024-08-02 10:30:00
No matching af mask found for 2021-06-20 09:35:00
No matching af mask found for 2020-07-08 10:00:00
No matching af mask found for 2023-09-18 14:15:00
No matching af mask found for 2021-07-21 10:30:00
No matching af mask found for 2023-07-08 09:50:00
No matching af mask found for 2021-06-18 11:30:00
No matching af mask found for 2020-06-08 13:00:00
No matching af mask found for 2020-08-12 10:25:00
No valid af mask found for 2024-08-21 12:00:00
No matching af mask found for 2022-06-24 10:10:00
No matching af mask found for 2021-08-31 13:50:00
No matching af mask found for 2021-07-09 10:10:00
No matching af mask found for 2022-06-19 13:10:00
No valid af mask found for 2024-07-30 10:05:00
No matching af mask found for 2021-06-24 14:10:00
No matching af mask found for 2021-09-14 10:35:00
No matching af mask found for 2022-07-24 13:30:00
No matching af mask found for 2021-07-30 08:55:00
No valid af mask found for 2024-06-10 10:35:00
No matching af mask found for 2023-08-01 13:25:00
No valid af mask found for 2024-09-21 11:25:00
No matching af mask found for 2021-09-08 14:30:00
No matching af mask found for 2021-06-09 11:35:00
No matching af mask found for 2022-06-12 13:00:00
No valid af mask found for 2023-09-28 13:05:00
No matching af mask found for 2023-07-23 12:10:00
No matching af mask found for 2020-09-19 13:05:00
No valid af mask found for 2024-08-01 14:50:00
No matching af mask found for 2020-06-26 14:30:00
No matching af mask found for 2021-07-29 13:05:00
No valid af mask found for 2024-08-27 12:40:00
No valid af mask found for 2024-09-01 14:30:00
No matching af mask found for 2021-09-21 10:50:00
No matching af mask found for 2022-06-22 13:35:00
No valid af mask found for 2023-09-28 14:40:00
No matching af mask found for 2022-06-20 12:15:00
No matching af mask found for 2022-09-09 11:00:00
No matching af mask found for 2021-09-26 14:20:00
No matching af mask found for 2023-06-25 08:55:00
No matching af mask found for 2021-07-15 12:50:00
No matching af mask found for 2022-06-02 12:30:00
No matching af mask found for 2020-09-12 13:00:00
No matching af mask found for 2021-07-03 09:10:00
No matching af mask found for 2022-08-15 12:55:00
No matching af mask found for 2023-08-10 11:40:00
No matching af mask found for 2020-08-14 10:15:00
No matching af mask found for 2021-09-28 10:50:00
No matching af mask found for 2023-08-24 09:55:00
No matching af mask found for 2021-08-02 12:35:00
No matching af mask found for 2023-07-10 12:45:00
No valid af mask found for 2024-06-21 13:10:00
No matching af mask found for 2020-09-10 11:40:00
No valid af mask found for 2024-09-02 13:30:00
No matching af mask found for 2021-06-14 11:55:00
No matching af mask found for 2022-08-29 13:00:00
No valid af mask found for 2024-07-11 13:35:00
No matching af mask found for 2020-07-07 14:10:00
No matching af mask found for 2020-09-09 14:15:00
No matching af mask found for 2023-08-14 11:10:00
No valid af mask found for 2024-07-13 15:05:00
No valid af mask found for 2024-07-11 13:40:00
No matching af mask found for 2023-07-17 12:50:00
No matching af mask found for 2023-08-15 10:05:00
No valid af mask found for 2024-06-13 14:20:00
No matching af mask found for 2023-07-03 11:15:00
No matching af mask found for 2021-09-09 10:20:00
No matching af mask found for 2023-07-05 14:15:00
No valid af mask found for 2024-08-30 14:40:00
No matching af mask found for 2023-08-27 11:55:00
No matching af mask found for 2020-09-30 12:45:00
No matching af mask found for 2023-06-30 12:20:00
No matching af mask found for 2020-07-25 09:00:00
No matching af mask found for 2021-07-24 12:45:00
No matching af mask found for 2020-08-22 09:30:00
No matching af mask found for 2023-06-28 14:15:00
No valid af mask found for 2024-07-17 14:30:00
No matching af mask found for 2021-06-15 11:00:00
No matching af mask found for 2022-07-14 09:35:00
No valid af mask found for 2023-09-26 11:35:00
No valid af mask found for 2024-07-02 10:45:00
No valid af mask found for 2024-09-19 15:05:00
No matching af mask found for 2023-09-05 11:40:00
No matching af mask found for 2022-09-05 14:45:00
No valid af mask found for 2023-09-28 13:00:00
No matching af mask found for 2020-09-17 11:40:00
No matching af mask found for 2020-09-22 13:40:00
No matching af mask found for 2020-07-13 13:35:00
No valid af mask found for 2024-06-07 15:05:00
No valid af mask found for 2024-06-24 13:40:00
No valid af mask found for 2024-08-10 12:40:00
No matching af mask found for 2022-07-23 11:10:00
No matching af mask found for 2020-08-26 09:00:00
No matching af mask found for 2020-09-09 10:55:00
No matching af mask found for 2021-09-07 10:35:00
No matching af mask found for 2020-06-19 09:25:00
No matching af mask found for 2022-06-21 11:20:00
No matching af mask found for 2022-08-06 14:40:00
No matching af mask found for 2020-07-15 13:20:00
No matching af mask found for 2022-07-18 10:55:00
No valid af mask found for 2024-09-15 14:00:00
No matching af mask found for 2021-07-25 11:45:00
No matching af mask found for 2020-06-25 10:30:00
No matching af mask found for 2020-09-02 12:30:00
No matching af mask found for 2022-08-02 11:45:00
No matching af mask found for 2020-09-15 13:35:00
No valid af mask found for 2024-07-26 14:00:00
No matching af mask found for 2020-07-27 12:05:00
No matching af mask found for 2023-06-17 11:30:00
No matching af mask found for 2020-08-10 13:55:00
No matching af mask found for 2022-07-14 12:55:00
No matching af mask found for 2022-08-13 09:40:00
No matching af mask found for 2020-09-08 10:15:00
No matching af mask found for 2021-07-25 13:25:00
No matching af mask found for 2023-06-23 10:45:00
No matching af mask found for 2023-09-10 10:20:00
No matching af mask found for 2023-09-06 09:10:00
No matching af mask found for 2020-09-09 12:30:00
No matching af mask found for 2022-06-13 13:45:00
No matching af mask found for 2023-06-18 12:15:00
No valid af mask found for 2024-07-27 11:20:00
No matching af mask found for 2021-07-18 11:45:00
No matching af mask found for 2023-09-12 15:00:00
No matching af mask found for 2020-06-30 10:45:00
No valid af mask found for 2024-07-14 12:25:00
No matching af mask found for 2022-07-03 10:00:00
No matching af mask found for 2023-07-08 14:45:00
No valid af mask found for 2024-06-05 12:15:00
No matching af mask found for 2022-06-27 14:00:00
No matching af mask found for 2022-07-20 10:40:00
No valid af mask found for 2023-09-22 10:30:00
No matching af mask found for 2020-08-17 12:25:00
No matching af mask found for 2022-07-04 12:25:00
No matching af mask found for 2020-09-25 12:35:00
No valid af mask found for 2024-08-03 14:30:00
No matching af mask found for 2020-07-04 10:25:00
No matching af mask found for 2023-08-18 12:15:00
No valid af mask found for 2024-06-15 12:20:00
No matching af mask found for 2023-08-27 10:25:00
No matching af mask found for 2021-07-15 14:30:00
No valid af mask found for 2024-08-20 09:40:00
No matching af mask found for 2021-06-15 10:55:00
No matching af mask found for 2020-09-10 10:00:00
No matching af mask found for 2022-09-14 14:35:00
No valid af mask found for 2024-08-11 10:05:00
No matching af mask found for 2022-07-27 09:10:00
No matching af mask found for 2022-07-26 11:35:00
No matching af mask found for 2023-08-07 12:40:00
No matching af mask found for 2020-06-24 09:40:00
No matching af mask found for 2023-07-23 10:25:00
No valid af mask found for 2024-08-13 13:10:00
No matching af mask found for 2020-09-08 11:45:00
No matching af mask found for 2022-08-21 13:45:00
No matching af mask found for 2022-08-08 14:25:00
No matching af mask found for 2023-09-04 09:20:00
No matching af mask found for 2021-08-15 10:25:00
No matching af mask found for 2020-06-11 10:20:00
No valid af mask found for 2024-08-20 12:50:00
No matching af mask found for 2021-06-28 10:30:00
No matching af mask found for 2021-06-06 09:25:00
No matching af mask found for 2023-07-31 14:25:00
No matching af mask found for 2021-07-22 13:00:00
No matching af mask found for 2022-09-19 10:00:00
No valid af mask found for 2024-08-06 10:00:00
No matching af mask found for 2023-08-06 10:30:00
No valid af mask found for 2024-07-12 12:40:00
No matching af mask found for 2022-09-07 09:35:00
No matching af mask found for 2020-07-22 11:45:00
No matching af mask found for 2021-08-12 11:35:00
No matching af mask found for 2020-06-12 14:20:00
No matching af mask found for 2021-08-11 10:55:00
No matching af mask found for 2023-08-21 09:30:00
No matching af mask found for 2021-07-06 14:35:00
No valid af mask found for 2024-09-26 10:00:00
No matching af mask found for 2021-07-10 12:35:00
No valid af mask found for 2024-07-31 14:05:00
No matching af mask found for 2021-07-16 13:30:00
No matching af mask found for 2023-08-05 14:35:00
No valid af mask found for 2024-07-03 14:50:00
No valid af mask found for 2024-08-12 10:45:00
No matching af mask found for 2020-06-07 12:15:00
No matching af mask found for 2021-07-11 13:20:00
No valid af mask found for 2023-09-23 14:25:00
No matching af mask found for 2020-07-13 13:30:00
No matching af mask found for 2021-08-27 12:35:00
No matching af mask found for 2020-08-03 13:55:00
No matching af mask found for 2021-09-25 13:40:00
No matching af mask found for 2022-07-21 14:35:00
No matching af mask found for 2023-06-08 11:45:00
No valid af mask found for 2024-06-15 10:40:00
No matching af mask found for 2021-07-08 09:25:00
No valid af mask found for 2024-07-08 10:05:00
No matching af mask found for 2020-09-15 10:20:00
No matching af mask found for 2021-07-19 14:00:00
No matching af mask found for 2021-08-01 11:55:00
No matching af mask found for 2022-08-04 11:30:00
No matching af mask found for 2023-08-21 12:45:00
No matching af mask found for 2022-09-01 11:45:00
No matching af mask found for 2022-06-29 13:40:00
No valid af mask found for 2024-06-08 14:15:00
No matching af mask found for 2023-06-21 11:00:00
No matching af mask found for 2021-08-19 13:25:00
No matching af mask found for 2022-06-18 12:30:00
No valid af mask found for 2024-08-10 09:25:00
No matching af mask found for 2020-07-08 13:15:00
No matching af mask found for 2021-07-29 11:20:00
No valid af mask found for 2024-07-12 11:00:00
No matching af mask found for 2021-09-01 12:45:00
No matching af mask found for 2021-07-07 10:25:00
No matching af mask found for 2020-07-09 14:00:00
No valid af mask found for 2024-09-26 09:55:00
No matching af mask found for 2023-07-20 09:55:00
No matching af mask found for 2022-08-06 11:20:00
No matching af mask found for 2023-07-28 14:00:00
No matching af mask found for 2022-06-18 14:05:00
No valid af mask found for 2024-09-10 13:55:00
No matching af mask found for 2020-08-03 12:15:00
No valid af mask found for 2024-07-16 10:35:00
No matching af mask found for 2022-06-25 14:05:00
No matching af mask found for 2021-08-12 13:15:00
No matching af mask found for 2021-07-30 12:05:00
No valid af mask found for 2023-09-23 09:35:00
No matching af mask found for 2022-06-03 13:15:00
No matching af mask found for 2023-08-28 11:00:00
No matching af mask found for 2021-07-04 09:50:00
No matching af mask found for 2023-07-02 12:15:00
No matching af mask found for 2022-09-15 11:55:00
No valid af mask found for 2024-09-11 11:15:00
No matching af mask found for 2021-07-01 10:55:00
No matching af mask found for 2022-09-06 08:55:00
No matching af mask found for 2022-06-30 09:35:00
No matching af mask found for 2022-07-15 13:40:00
No matching af mask found for 2023-08-11 13:50:00
No matching af mask found for 2023-07-25 11:50:00
No matching af mask found for 2021-08-07 11:15:00
No matching af mask found for 2022-07-23 11:15:00
No valid af mask found for 2024-06-14 15:00:00
No matching af mask found for 2020-08-14 13:35:00
No matching af mask found for 2021-07-31 12:45:00
No matching af mask found for 2023-06-07 12:45:00
No matching af mask found for 2022-09-24 10:15:00
No valid af mask found for 2024-08-26 13:45:00
No matching af mask found for 2021-09-13 11:35:00
No matching af mask found for 2022-06-18 10:45:00
No valid af mask found for 2024-07-30 13:25:00
No matching af mask found for 2021-08-03 10:00:00
No matching af mask found for 2021-06-05 10:20:00
No matching af mask found for 2023-06-01 10:10:00
No valid af mask found for 2024-08-30 13:00:00
No matching af mask found for 2020-09-14 09:35:00
No matching af mask found for 2021-09-17 12:55:00
No valid af mask found for 2023-09-22 12:00:00
No matching af mask found for 2022-07-22 10:30:00
No valid af mask found for 2024-08-11 15:00:00
No matching af mask found for 2020-07-28 11:15:00
No matching af mask found for 2020-09-10 13:20:00
No valid af mask found for 2024-07-20 14:50:00
No matching af mask found for 2020-09-25 10:50:00
No matching af mask found for 2023-09-12 11:40:00
No valid af mask found for 2024-06-28 11:25:00
No valid af mask found for 2023-09-19 14:55:00
No matching af mask found for 2023-08-15 11:45:00
No matching af mask found for 2021-08-18 12:40:00
No valid af mask found for 2024-08-18 11:35:00
No matching af mask found for 2021-08-11 14:10:00
No valid af mask found for 2024-08-02 13:55:00
No matching af mask found for 2021-06-16 13:25:00
No matching af mask found for 2021-07-10 12:30:00
No matching af mask found for 2022-08-20 09:45:00
No matching af mask found for 2020-09-22 10:25:00
No matching af mask found for 2022-09-25 09:15:00
No matching af mask found for 2023-09-12 10:00:00
No matching af mask found for 2021-08-31 12:05:00
No matching af mask found for 2022-08-20 11:25:00
No matching af mask found for 2020-08-06 14:20:00
No matching af mask found for 2020-07-17 13:05:00
No matching af mask found for 2020-09-04 10:30:00
No matching af mask found for 2021-09-29 13:10:00
No matching af mask found for 2023-08-23 12:30:00
No matching af mask found for 2020-06-22 11:35:00
No matching af mask found for 2022-09-06 10:30:00
No matching af mask found for 2021-06-27 09:40:00
No matching af mask found for 2021-09-10 11:00:00
No matching af mask found for 2021-09-08 09:35:00
No matching af mask found for 2021-09-25 12:00:00
No matching af mask found for 2023-06-09 14:00:00
No matching af mask found for 2021-09-08 11:15:00
No matching af mask found for 2020-08-23 10:15:00
No matching af mask found for 2023-09-10 13:30:00
No matching af mask found for 2020-07-10 13:05:00
No matching af mask found for 2023-08-08 10:10:00
No matching af mask found for 2023-06-17 11:25:00
No matching af mask found for 2021-07-05 12:10:00
No valid af mask found for 2024-09-17 10:30:00
No matching af mask found for 2020-08-07 13:25:00
No matching af mask found for 2022-08-12 12:25:00
No valid af mask found for 2024-08-04 13:35:00
No matching af mask found for 2023-07-25 13:25:00
No matching af mask found for 2020-07-30 12:35:00
No matching af mask found for 2021-07-27 13:10:00
No matching af mask found for 2023-09-12 13:15:00
No matching af mask found for 2020-08-06 11:00:00
No matching af mask found for 2022-09-14 11:15:00

In [27]:
df_matches

      timestamp_cm   timestamp_msg
0   20210930090500  20210930092743
1   20210930090000  20210930092743
2   20230914144500  20230914151241
3   20210618131000  20210618135744
4   20210907085500  20210907095742
5   20230915135000  20230915145742
6   20210622142500  20210622161242
7   20210601123000  20210601125743
8   20210907090000  20210907095742
9   20210828131500  20210828144242
10  20210618130500  20210618135744
11  20210601122000  20210601125743
12  20210612102500  20210612104243
13  20210820105000  20210820105743
14  20220601114000  20220601114243
15  20230914144000  20230914151241
16  20220815093000  20220815101242
17  20210828131000  20210828144242
18  20230915134500  20230915145742
19  20230701112500  20230701115742
20  20210601122500  20210601125743
21  20230919095500  20230919101242
22  20210612103000  20210612104243
23  20220601100500  20220601114243
24  20220815093500  20220815101242
25  20210809124000  20210809125744
26  20220604135500  20220604152742
27  20210809110500  20210809125744
28  20210612085500  20210612104243
29  20210809110000  20210809125744
30  20210809111000  20210809125744
31  20210622142000  20210622161242
32  20210828132000  20210828144242
33  20210820091000  20210820105743
34  20220601101000  20220601114243
35  20210820104500  20210820105743
36  20230701113000  20230701115742
37  20230919100000  20230919101242
38  20220604135000  20220604152742
39  20210809124500  20210809125744

In [28]:
print(len(df_matches))

40

In [29]:
ref_nat_file = '/mnt/outputs/L1b/MSG4-SEVI-MSG15-0100-NA-20210601232742.451000000Z-NA.nat'
scn = Scene(reader="seviri_l1b_native", filenames=[ref_nat_file])
datasets = scn.available_dataset_names()
scn.load(datasets[1:], generate=False)
dataset = scn['IR_016']
crs_wkt = dataset.attrs['area'].crs_wkt

In [30]:
def count_nans(da, extra_value = None):
    nans_da = da.isnull().sum().item()
    N = da.size
    nan_pct = float(nans_da/N * 100)
    print(f"NaNs: {nan_pct:.2f}%")
    if extra_value:
        values_da =  np.count_nonzero(da.values == -1) 
        final = nans_da + values_da
        nan_pct = float(final/N * 100)
        print(f"NaNs: {nan_pct:.2f}%")
    return nan_pct

In [31]:
for index, row in df_matches.iterrows():
    save_path = os.path.join(outpath, row['timestamp_msg']+'_msg_modis.nc')
    msg_im = xr.open_dataset(os.path.join(seviri_path, '20200929121242_msg.nc'))
    modis_im_name = cm_df[cm_df.utimes == row['timestamp_cm']].name.values[0]
    modis_im = rioxarray.open_rasterio(os.path.join(modis_cm_path, modis_im_name))
    msg_reprojected = reproject_msg_image(msg_im, crs_wkt)
    if check_overlap(modis_im, msg_reprojected):
        msg_clipped, modis_clipped = clip_and_align(msg_reprojected, modis_im)
    else:
        continue
    nans_msg = count_nans(msg_clipped)
    nans_modis = count_nans(modis_clipped, -1)
    if nans_msg<90 and nans_modis<90:
        modis_clipped = modis_clipped.assign_coords(band=["modis_cm"])
        both = xr.concat([msg_clipped, modis_clipped], dim="band")
        both.attrs['modis_time'] = row['timestamp_cm']
        both.attrs['modis_image'] = cm_df[cm_df.utimes == row['timestamp_cm']].name.values[0]
        both.to_netcdf(save_path)
    else:
        continue

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/seviri/geoprocessed/20200929121242_msg.nc'